vcver:
 - 14.3
 - 14.3
 - 14.2
 - 14.1
vsyear:
 - 2022
 - 2022
 - 2019
 - 2017
vsver:
 - 17
 - 17
 - 16
 - 15
runtime_version:
 # the azure/github images only contain the latest minor version per vs-line;
 # if there is a use-case for having older minor versions, they can be added when requested.
 - 14.36.32532
 - 14.36.32532
 - 14.29.30139
 - 14.16.27033
# the VS update version.  This is the middle digit in the version
# reported in the VS help->about UI.  It is perhaps a more readily
# referenceable number.
update_version:
 - 7
 - 7
 - 11
 - 9
# This is the version number reported by cl.exe
cl_version:
 - 19.37.32822
 - 19.37.32822
 - 19.29.30139
 - 19.16.27033
# This is the uuid in the URL; redirect can be resolved e.g. as follows
# curl -ILSs https://aka.ms/vs/17/release/vc_redist.x64.exe | grep "Location:"
# curl -ILSs https://aka.ms/vs/17/release/vc_redist.arm64.exe | grep "Location:"
uuid:
 - eaab1f82-787d-4fd7-8c73-f782341a0c63
 - eaab1f82-787d-4fd7-8c73-f782341a0c63
 - b929b7fe-5c89-4553-9abe-6324631dcc3a
 - 4100b84d-1b4d-487d-9f89-1354a7138c8f
sha256:
 - 37342E0ABDAEAE0297F64A889F842AC9453139639FB0178C0754A7D2F330043A
 - 917C37D816488545B70AFFD77D6E486E4DD27E2ECE63F6BBAAF486B178B2B888
 - 296F96CD102250636BCD23AB6E6CF70935337B1BBB3507FE8521D8D9CFAA932F
 - 5B0CBB977F2F5253B1EBE5C9D30EDBDA35DBD68FB70DE7AF5FAAC6423DB575B5
cross_target_platform:
 - win-arm64
 - win-64
 - win-64
 - win-64

zip_keys:
 - - vcver
   - vsyear
   - vsver
   - runtime_version
   - update_version
   - cl_version
   - uuid
   - sha256
   - cross_target_platform
