# Switch the version of this recipe based on the VC_VERSION environment variable.
{% set VERSION = os.environ.get('VC_VERSION', '9')|string %}
{% set runtime_years = {'9': '2008', '10': '2010', '14': '2015'} %}
{% set runtime_year = runtime_years[VERSION] %}

package:
  name: vc
  version: {{ VERSION }}

build:
  number: 0
  track_features:
    - vc{{ VERSION }}
  skip: true  # [not win]

requirements:
  run:
    - vs{{ runtime_year }}_runtime

# We don't need to test anything here - this is purely a metapackage.
test: {}

about:
  home: https://github.com/conda/conda/wiki/VC-features
  license: BSD 3-Clause
  summary: A meta-package to track VC features.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - pelson
    - patricksnape
    - msarahan
