matrix:
- [[VC_VERSION, 9]]
- [[VC_VERSION, 10]]
- [[VC_VERSION, 14]]
travis:
  secure:
    BINSTAR_TOKEN: cZk1nMkzrIzOyF0/D+xh0w3wJBESNlD1eKz+z9DKriTAk71Cof06LyCtNf5ltkAeThMuemiWDGQlMED2KjIl+03sPR9wg9MRwRQGBVDHhNDfxSfOjkgUpv4MlmTiz9LQbBxlvYC5WsiG6yS/M/MDHqDGDzyVLZjr65QJqCB4egNxFdZ1hK0iscmm5M1OUpk8K5DhpSmAL0DwmZ6Uqz6l64ROovrRSGEEYevmgoJcu29a0d4IlAyjZoM4UcNZTb58RuSYHDwP9lGbR6C238RC/7+K/GROqubMBGKOMrwTnhYLtPDlDjw5WO5+sxIYI9spOqShs16/XDjVidnfkcgKiSzFwTik+lMT96eq4I/8gi9QVcR5AnWiSbnrf1CPfntMuqe8vLVWrnO9xiaakypYvdR5NXmvfWrBVznGSQJHhDwEtw8tuqVC1B6kkdOagrocsbw/zklM+wR6iSSVAt5RfloLHQ1KUfjyuUWvLhgqY3Spk+p4WM+LrMttW/HU+Wr9RCfXB5lxP37OlkVv9uhdIh723nwOpuEimFhWT9DBMLTQCS8gRnv5AkF1NhnVswkgkzeVZwzoBRMbITUGbXe5ql3yFN/nocq7TnM3Fg/lanCrtP7Pp0DklRSUMrr1+9FP1vyEDEVhsB/C99Ie4hEyMcVvQr2aSSNnKPDLBQS8Wh0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
