# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_cl_version19.16.27033cross_t_h7a8626972c:
        CONFIG: win_64_cl_version19.16.27033cross_t_h7a8626972c
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cl_version19.16.27033cross_t_h7a8626972c
      win_64_cl_version19.28.29325cross_t_ha590b1728a:
        CONFIG: win_64_cl_version19.28.29325cross_t_ha590b1728a
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cl_version19.28.29325cross_t_ha590b1728a
      win_64_cl_version19.29.30139cross_t_h16fbe5123a:
        CONFIG: win_64_cl_version19.29.30139cross_t_h16fbe5123a
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cl_version19.29.30139cross_t_h16fbe5123a
      win_64_cl_version19.33.31629cross_t_h7c0b0521c9:
        CONFIG: win_64_cl_version19.33.31629cross_t_h7c0b0521c9
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cl_version19.33.31629cross_t_h7c0b0521c9
      win_64_cl_version19.34.31933cross_t_ha1b23476d0:
        CONFIG: win_64_cl_version19.34.31933cross_t_ha1b23476d0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cl_version19.34.31933cross_t_ha1b23476d0
      win_64_cl_version19.34.31933cross_t_hce3d1cfb15:
        CONFIG: win_64_cl_version19.34.31933cross_t_hce3d1cfb15
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cl_version19.34.31933cross_t_hce3d1cfb15
      win_arm64_cl_version19.16.27033cros_h10441f7228:
        CONFIG: win_arm64_cl_version19.16.27033cros_h10441f7228
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_arm64_cl_version19.16.27033cros_h10441f7228
      win_arm64_cl_version19.28.29325cros_h5220c15796:
        CONFIG: win_arm64_cl_version19.28.29325cros_h5220c15796
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_arm64_cl_version19.28.29325cros_h5220c15796
      win_arm64_cl_version19.29.30139cros_h5ab1bbeecd:
        CONFIG: win_arm64_cl_version19.29.30139cros_h5ab1bbeecd
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_arm64_cl_version19.29.30139cros_h5ab1bbeecd
      win_arm64_cl_version19.33.31629cros_hc9d89599e7:
        CONFIG: win_arm64_cl_version19.33.31629cros_hc9d89599e7
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_arm64_cl_version19.33.31629cros_hc9d89599e7
      win_arm64_cl_version19.34.31933cros_h8344a86c8a:
        CONFIG: win_arm64_cl_version19.34.31933cros_h8344a86c8a
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_arm64_cl_version19.34.31933cros_h8344a86c8a
      win_arm64_cl_version19.34.31933cros_hcd8d0d9975:
        CONFIG: win_arm64_cl_version19.34.31933cros_hcd8d0d9975
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_arm64_cl_version19.34.31933cros_hcd8d0d9975
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_TEMP: D:\\tmp

  steps:
    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call activate base
        mamba.exe install "python=3.10" conda-build conda pip boa conda-forge-ci-setup=3 -c conda-forge --strict-channel-priority --yes
      displayName: Install conda-build

    - script: set PYTHONUNBUFFERED=1
      displayName: Set PYTHONUNBUFFERED

    # Configure the VM
    - script: |
        call activate base
        setup_conda_rc .\ ".\recipe" .\.ci_support\%CONFIG%.yaml
      displayName: conda-forge CI setup

    # Configure the VM.
    - script: |
        set "CI=azure"
        call activate base
        run_conda_forge_build_setup
      displayName: conda-forge build setup

    - script: |
        call activate base
        if EXIST LICENSE.txt (
          copy LICENSE.txt "recipe\\recipe-scripts-license.txt"
        )
        conda.exe mambabuild "recipe" -m .ci_support\%CONFIG%.yaml --suppress-variables
      displayName: Build recipe
      env:
        PYTHONUNBUFFERED: 1
    - script: |
        set CI=azure
        set CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        set FEEDSTOCK_NAME=$(build.Repository.Name)
        set ARTIFACT_STAGING_DIR=$(Build.ArtifactStagingDirectory)
        set CONDA_BLD_DIR=$(CONDA_BLD_PATH)
        set BLD_ARTIFACT_PREFIX=conda_artifacts
        if "%AGENT_JOBSTATUS%" == "Failed" (
            set ENV_ARTIFACT_PREFIX=conda_envs
        )
        call ".scripts\create_conda_build_artifacts.bat"
      displayName: Prepare conda build artifacts
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      displayName: Store conda build artifacts
      condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(BLD_ARTIFACT_PATH)
        artifactName: $(BLD_ARTIFACT_NAME)

    - task: PublishPipelineArtifact@1
      displayName: Store conda build environment artifacts
      condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(ENV_ARTIFACT_PATH)
        artifactName: $(ENV_ARTIFACT_NAME)
    - script: |
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        call activate base
        validate_recipe_outputs "%FEEDSTOCK_NAME%"
      displayName: Validate Recipe Outputs

    - script: |
        set "GIT_BRANCH=%BUILD_SOURCEBRANCHNAME%"
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        set "TEMP=$(UPLOAD_TEMP)"
        if not exist "%TEMP%\" md "%TEMP%"
        set "TMP=%TEMP%"
        call activate base
        upload_package --validate --feedstock-name="%FEEDSTOCK_NAME%" .\ ".\recipe" .ci_support\%CONFIG%.yaml
      displayName: Upload package
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
      condition: and(succeeded(), not(eq(variables['UPLOAD_PACKAGES'], 'False')), not(eq(variables['Build.Reason'], 'PullRequest')))